#! /usr/bin/env escript
%% -*- erlang -*-
%%! -pa ebin deps/jsx/ebin

main(_Args) ->
    sample:ensure_started(),
    Api = twitter:new(sample:app_post_auth()),
    {_, Tweets} = twitter_rest:get(Api, "statuses/user_timeline", [{screen_name, "Hurriyet"}, {count, 1}]),
    io:format("~p~n", [Tweets]).
